-- 뷰
-- <관리자> 과목 정보 출력 뷰 생성 (VIEW_SUB_INFO) - 확인완료
CREATE OR REPLACE VIEW VIEW_SUB_INFO
AS
SELECT C.COURSE_NAME "과정명", R.ROOM_NAME "강의실명", S.SUBJECT_NAME "과목명"
     , (TO_CHAR(SD.SUB_BEGIN) || ' ~ ' || TO_CHAR(SD.SUB_END)) "과목기간", B.BOOK_NAME "교재명"
     , P.PRF_NAME "교수자명"
FROM SUB_DETAIL SD, BOOK B, SUBJECT S, CR_DETAIL CD, CLASSROOM R, COURSE C, PROF P 
WHERE SD.BOOK_NO = B.BOOK_NO
  AND SD.SUBJECT_NO = S.SUBJECT_NO
  AND SD.CR_NO = CD.CR_NO
  AND CD.COURSE_NO = C.COURSE_NO
  AND CD.ROOM_NO = R.ROOM_NO
  AND CD.PRF_NO = P.PRF_NO;

SELECT *
FROM VIEW_SUB_INFO;


-- <관리자> 과정 정보 출력 뷰 생성 (VIEW VIEW_CR_INFO) - 확인완료
CREATE OR REPLACE VIEW VIEW_CR_INFO
AS
SELECT C3.COURSE_NAME "과정명", C1.ROOM_NAME "강의실명", J.SUBJECT_NAME "과목명",TO_CHAR(S1.SUB_BEGIN) ||' ~ '||
      TO_CHAR(S1.SUB_END) "과목기간", B.BOOK_NAME "교재명", P.PRF_NAME "교수자명"
FROM CLASSROOM C1 JOIN CR_DETAIL C2 
ON C1.ROOM_NO = C2.ROOM_NO
    JOIN COURSE C3
      ON C2.COURSE_NO = C3.COURSE_NO
        JOIN SUB_DETAIL S1
          ON C2.CR_NO = S1.CR_NO
                JOIN SUBJECT J
                  ON J.SUBJECT_NO = S1.SUBJECT_NO
                        JOIN BOOK B
                          ON B.BOOK_NO = S1.BOOK_NO
                                JOIN PROF P
                                  ON P.PRF_NO = C2.PRF_NO;
                  
SELECT *                
FROM VIEW_CR_INFO;

-- <관리자> 교수자 정보 출력 뷰 생성 (VIEW_PROF_INFO) - 확인완료
CREATE OR REPLACE VIEW VIEW_PROF_INFO
AS
SELECT P.PRF_NAME "교수명", S.SUBJECT_NAME "과목명",  SD.SUB_BEGIN || ' ~ ' || SD.SUB_END "과목기간"
     , B.BOOK_NAME "교재명", C.ROOM_NAME "강의실"
     , CASE WHEN SYSDATE < SD.SUB_BEGIN THEN '예정'
            WHEN SYSDATE >= SD.SUB_BEGIN AND SYSDATE <= SD.SUB_END THEN '진행중'
            WHEN SYSDATE > SD.SUB_END THEN '완료'
            ELSE '확인불가'
       END "강의진행여부"
FROM PROF P LEFT JOIN CR_DETAIL CD
    ON P.PRF_NO = CD.PRF_NO
    LEFT JOIN CLASSROOM C
        ON CD.ROOM_NO = C.ROOM_NO
            LEFT JOIN SUB_DETAIL SD
            ON CD.CR_NO = SD.CR_NO
                LEFT JOIN SUBJECT S
                ON SD.SUBJECT_NO = S.SUBJECT_NO
                    LEFT JOIN BOOK B
                    ON SD.BOOK_NO = B.BOOK_NO;

SELECT *
FROM VIEW_PROF_INFO;

-- <관리자> 학생 정보 출력 뷰 생성 (VIEW_STUDENT_INFO) - 확인완료
CREATE OR REPLACE VIEW VIEW_STUDENT_INFO
AS
SELECT ST.STD_NAME "학생명", C.COURSE_NAME "과정명" , S.SUBJECT_NAME "과목명" ,(ATTEND_SC + WRITE_SC + PRACTICE_SC) "총점"
FROM STUDENTS ST LEFT JOIN APPLY A
  ON ST.STD_NO = A.STD_NO
    LEFT JOIN SCORE SC
      ON A.APPLY_NO = SC.APPLY_NO
        LEFT JOIN SUB_DETAIL SD
          ON SD.SUB_NO =SC.SUB_NO
            LEFT JOIN SUBJECT S
              ON S.SUBJECT_NO = SD.SUBJECT_NO
               LEFT JOIN CR_DETAIL CD
                 ON CD.CR_NO = SD.CR_NO
                   LEFT JOIN COURSE C 
                    ON C.COURSE_NO = CD.COURSE_NO;

SELECT *
FROM VIEW_STUDENT_INFO;

-- <교수측> 성적 정보 출력 뷰 생성 (VIEW_SCORE_INFO) -- 확인완료
/*
CREATE OR REPLACE VIEW VIEW_SCORE_INFO
AS
SELECT P.PRF_NAME 교수명
     , SB.SUBJECT_NAME 과목명
     , TO_CHAR(SD.SUB_BEGIN) || ' ~ ' ||  TO_CHAR(SD.SUB_END) 과목기간
     , B.BOOK_NAME 교재명
     , S.STD_NAME 학생명
     , SC.ATTEND_SC  출결
     , SC.WRITE_SC   필기
     , SC.PRACTICE_SC    실기
     , (SC.ATTEND_SC + SC.WRITE_SC + SC.PRACTICE_SC) 과목총점
     , RANK() OVER(PARTITION BY SB.SUBJECT_NAME ORDER BY NVL(SC.ATTEND_SC + SC.WRITE_SC + SC.PRACTICE_SC, 0) DESC) 과목등수
     , CASE WHEN F.FAIL_NO IS NOT NULL THEN 'Y'
            WHEN F.FAIL_NO IS NULL THEN 'N'
            ELSE 'ERROR'
       END  중도탈락여부
FROM APPLY A LEFT JOIN STUDENTS S
ON S.STD_NO = A.STD_NO
    LEFT JOIN SCORE SC
    ON A.APPLY_NO = SC.APPLY_NO
        LEFT JOIN FAIL F
        ON A.APPLY_NO = F.APPLY_NO
            LEFT JOIN SUB_DETAIL SD
            ON SC.SUB_NO = SD.SUB_NO
                LEFT JOIN CR_DETAIL CD
                ON SD.CR_NO = CD.CR_NO
                    LEFT JOIN PROF P
                    ON CD.PRF_NO = P.PRF_NO
                    LEFT JOIN SUBJECT SB
                    ON SD.SUBJECT_NO = SB.SUBJECT_NO
                        LEFT JOIN BOOK B
                        ON SD.BOOK_NO = B.BOOK_NO;
*/
CREATE OR REPLACE VIEW VIEW_SCOREPRF_INFO
AS
SELECT P.PRF_NAME 교수명, S.SUBJECT_NAME 과목명, TO_CHAR(SD.SUB_BEGIN) || ' ~ ' ||  TO_CHAR(SD.SUB_END) 과목기간, B.BOOK_NAME 교재명
FROM PROF P LEFT JOIN CR_DETAIL CD
ON P.PRF_NO = CD.PRF_NO
    LEFT JOIN COURSE C
    ON CD.COURSE_NO = C.COURSE_NO
        LEFT JOIN SUB_DETAIL SD
        ON CD.CR_NO = SD.CR_NO
            LEFT JOIN SUBJECT S
            ON SD.SUBJECT_NO = S.SUBJECT_NO
                LEFT JOIN BOOK B
                ON SD.BOOK_NO = B.BOOK_NO;

CREATE OR REPLACE VIEW VIEW_SCORE_INFO
AS               
SELECT SB.SUBJECT_NAME 과목명
     , S.STD_NAME 학생명
     , SC.ATTEND_SC  출결
     , SC.WRITE_SC   필기
     , SC.PRACTICE_SC    실기
     , (SC.ATTEND_SC + SC.WRITE_SC + SC.PRACTICE_SC) 과목총점
     , RANK() OVER(PARTITION BY SB.SUBJECT_NAME ORDER BY NVL(SC.ATTEND_SC + SC.WRITE_SC + SC.PRACTICE_SC, 0) DESC) 과목등수
     , CASE WHEN F.FAIL_NO IS NOT NULL THEN 'Y'
            WHEN F.FAIL_NO IS NULL THEN 'N'
            ELSE 'ERROR'
       END  중도탈락여부
FROM APPLY A LEFT JOIN STUDENTS S
ON A. STD_NO = S.STD_NO
    LEFT JOIN SCORE SC
    ON A.APPLY_NO = SC.APPLY_NO
        LEFT JOIN FAIL F
        ON A.APPLY_NO = F.APPLY_NO
            LEFT JOIN SUB_DETAIL SD
            ON SD.SUB_NO = SC.SUB_NO
                LEFT JOIN SUBJECT SB
                ON SD.SUBJECT_NO = SB.SUBJECT_NO;
SELECT *
FROM VIEW_SCOREPRF_INFO;


SELECT *
FROM VIEW_SCORE_INFO
WHERE 과목명 = 'Oracle Database';

-- <학생> 성적 정보 출력 뷰 생성 (VIEW_STUDENTSC_INFO) - 확인완료
CREATE OR REPLACE VIEW VIEW_STUDENTSC_INFO
AS
SELECT   S.STD_NO "학생코드"
       , S.STD_NAME "학생이름"
       , C.COURSE_NAME "과정명"
       , SB.SUBJECT_NAME "과목명"
       , TO_CHAR(CBD.CR_BEGIN,'YYYY-MM-DD') || ' ~ ' || TO_CHAR(CBD.CR_END,'YYYY-MM-DD') "과정기간"
       , TO_CHAR(SBD.SUB_BEGIN,'YYYY-MM-DD') || ' ~ ' || TO_CHAR(SBD.SUB_END,'YYYY-MM-DD') "해당과목교육기간"
       , B.BOOK_NAME "교재명"
       , CASE WHEN (SBD.SUB_END < SYSDATE) THEN (SC.ATTEND_SC) ELSE 0 END "출결" 
       , CASE WHEN (SBD.SUB_END < SYSDATE) THEN (SC.WRITE_SC) ELSE 0 END "필기" 
       , CASE WHEN (SBD.SUB_END < SYSDATE) THEN (SC.PRACTICE_SC) ELSE 0 END "실기" 
       , CASE WHEN (SBD.SUB_END < SYSDATE) THEN (SC.ATTEND_SC + SC.WRITE_SC + SC.PRACTICE_SC) ELSE 0 END "총점"
--       , SC.ATTEND_SC "출결" 
--       , SC.WRITE_SC "필기"
--       , SC.PRACTICE_SC "실기"
--       , SC.ATTEND_SC + SC.WRITE_SC + SC.PRACTICE_SC "총점"
     , RANK() OVER (PARTITION BY SUBJECT_NAME ORDER BY (SC. ATTEND_SC + SC.WRITE_SC + SC.PRACTICE_SC) DESC) "등수"
     , F.FAIL_DATE "중도탈락일자"
     , FR.FR "탈락사유"
FROM COURSE C JOIN CR_DETAIL CBD
    ON C.COURSE_NO = CBD.COURSE_NO
    JOIN SUB_DETAIL SBD 
    ON SBD.CR_NO = CBD.CR_NO
    JOIN SUBJECT SB
    ON SBD.SUBJECT_NO = SB.SUBJECT_NO
    JOIN BOOK B
    ON B.BOOK_NO = SBD.BOOK_NO
    JOIN SCORE SC
    ON SC.SUB_NO = SBD.SUB_NO
    JOIN APPLY A
    ON A.APPLY_NO = SC.APPLY_NO
    JOIN STUDENTS S
    ON S.STD_NO = A.STD_NO
    LEFT JOIN FAIL F
    ON A.APPLY_NO = F.APPLY_NO
    LEFT JOIN FAIL_REASON FR
    ON  F.FR_NO = FR.FR_NO;
    
SELECT *
FROM VIEW_STUDENTSC_INFO;  
    
    